# Generated by Django 4.1.7 on 2023-06-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pais_id', models.AutoField(primary_key=True, serialize=False)),
                ('pais_descripcion', models.CharField(max_length=25)),
                ('pais_abreviatura', models.CharField(blank=True, max_length=3)),
            ],
        ),
    ]
    