# Generated by Django 4.1.7 on 2023-02-26 21:12

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('departamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('departamento_descripcion', models.CharField(max_length=25)),
                ('departamento_nro', models.BigIntegerField()),
                ('departamento_abreviatura', models.CharField(blank=True, max_length=3)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.pais')),
            ],
        ),
    ]

