# Generated by Django 4.1.7 on 2023-06-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='capital_dpto',
            field=models.BooleanField(default=False),
        ),
    ]
