# Generated by Django 4.1.7 on 2023-06-20 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_empresa_nivelprioridad_parametro_permiso_persona_rol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='departamento',
            new_name='departamento_id',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='pais',
            new_name='pais_id',
        ),
    ]

