# Generated by Django 4.2.2 on 2023-06-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cola_cola_fecha_hora_atencion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='persona_fecha_nacimineto',
            new_name='persona_fecha_nacimiento',
        ),
    ]
